# Generated by Django 3.2.25 on 2024-04-10 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what_title', models.CharField(blank=True, max_length=50)),
                ('what_content', models.TextField(blank=True)),
                ('where_place', models.CharField(blank=True, max_length=50)),
                ('where_address', models.TextField(blank=True, max_length=255)),
                ('when_start', models.DateTimeField(blank=True)),
                ('when_end', models.DateTimeField(blank=True)),
                ('intention', models.TextField(blank=True, max_length=255)),
                ('event_image', models.ImageField(blank=True, default='ondego_event_placeholder/fhq6qy9kir3aw2ngkvlt', upload_to='ondego_events/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-when_start'],
            },
        ),
    ]
