# Generated by Django 3.2.25 on 2024-04-10 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='when_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
