# Generated by Django 3.2.25 on 2024-04-10 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20240410_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='when_start',
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now),
        ),
    ]
