# Generated by Django 3.2.25 on 2024-04-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_when_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='when_start',
            field=models.DateTimeField(blank=True),
        ),
    ]
