# Generated by Django 3.2.4 on 2024-07-03 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_when_start'),
        ('joinings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joining',
            name='event',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='joining', to='events.event'),
        ),
        migrations.AlterField(
            model_name='joining',
            name='joining_status',
            field=models.IntegerField(
                choices=[(1, 'Cannot'), (2, 'Joining'), (3, 'let me see')], default=1),
        ),
    ]
